### ISSUE TITLE
AST YAML to API Blueprint md: A resource is missing URI template error

### ISSUE THREAD

**Issue by rrarunan** [apiaryio/matter_compiler#1]
>  _version: 1.0

```
metadata:
FORMAT:
    value: 1A

name: <API name>
description: <API description>

resourceGroups:
- name: <resource group name>
  description: <resource group description>

  resources:
- name: <resource name>
  description: <resource description>
  uriTemplate: /testResource/{id}
```

  …<br>
  …

Error message: `Invalid input: A resource is missing URI template ('<resource name>' resource)`

Anything I'm doing wrong in the above YAML AST?
